name: 'Send to Linear'
description: 'Basic sync from GitHub Issues to Linear'
inputs:
  linear-team-id:
    description: Linear team to create the triage issue in
    required: true
  linear-api-key:
    description: Linear API key
    required: true
  linear-status-opened:
    description: Status ID of newly opened issues
    required: true
  linear-status-closed:
    description: Status ID of closed issues
    required: true
  linear-status-reopened:
    description: Status ID of reopened issues
    required: true
  github-token:
    description: GitHub Token
    required: true
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
