name: 'Send to Linear'
description: 'Basic sync from GitHub Issues to Linear'
inputs:
  linear-team-id:
    description: Linear team to create the triage issue in
    required: true
  linear-api-key:
    description: Linear API key
    required: true
  github-token:
    description: GitHub Token
    required: true
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
